export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_LOADING = "UPDATE_USER_INFO_LOADING";
export const UPDATE_USER_INFO_FAILED = "UPDATE_USER_INFO_FAILED";

export const UPDATE_KITCHEN_INFO = "UPDATE_KITCHEN_INFO";
